title:              DevJang
email:              wns8363@gmail.com
description:        게임을 하자. 게임을 만들자
author:             Hyeonjun Jang
baseurl:            ""
url:                "https://hyeonjun414.github.io"

# Social Profiles
twitter_username:   
github_username:    hyeonjun414
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

  